export const startups = [
  {
    id: '1',
    name: 'NeuralPay',
    tagline: 'AI-powered payment infrastructure for emerging markets',
    description: "NeuralPay uses deep learning to predict and prevent payment fraud while enabling instant cross-border transactions at 0.1% fees. We've processed $2M in transactions in our first 3 months.",
    industry: 'FinTech',
    stage: 'Seed',
    askAmount: '2M',
    equity: '8%',
    traction: '10K MAU',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 1243,
    comments: 89,
    bookmarks: 234,
    founder: { name: 'Alex Chen', title: 'CEO & Co-founder', bio: 'Ex-Stripe engineer, Stanford CS grad', avatar: null },
    team: [{ name: 'Alex Chen', role: 'CEO', avatar: null }, { name: 'Sarah Kim', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)
  },
  {
    id: '2',
    name: 'GreenLeap',
    tagline: 'Carbon credit marketplace for small businesses',
    description: 'GreenLeap makes it easy for SMBs to offset their carbon footprint through a verified marketplace. We aggregate small purchases to create institutional-grade carbon credits.',
    industry: 'CleanTech',
    stage: 'Pre-seed',
    askAmount: '500K',
    equity: '10%',
    traction: '500 businesses',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 876,
    comments: 43,
    bookmarks: 156,
    founder: { name: 'Maya Patel', title: 'CEO & Founder', bio: 'Ex-McKinsey, Climate Policy Expert', avatar: null },
    team: [{ name: 'Maya Patel', role: 'CEO', avatar: null }, { name: 'James Liu', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)
  },
  {
    id: '3',
    name: 'EduFlow',
    tagline: 'Adaptive learning platform powered by AI tutors',
    description: "EduFlow personalizes K-12 education using AI tutors that adapt to each student's learning style. Our platform has shown 40% improvement in test scores across 200 schools.",
    industry: 'EdTech',
    stage: 'Series A',
    askAmount: '10M',
    equity: '12%',
    traction: '50K students',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 2341,
    comments: 167,
    bookmarks: 445,
    founder: { name: 'Rachel Torres', title: 'CEO & Co-founder', bio: 'Former Google AI researcher', avatar: null },
    team: [{ name: 'Rachel Torres', role: 'CEO', avatar: null }, { name: 'David Park', role: 'CPO', avatar: null }, { name: 'Lena Schmidt', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
  },
  {
    id: '4',
    name: 'MedBridge',
    tagline: 'Connecting rural patients with specialist doctors via AI triage',
    description: "MedBridge uses computer vision and NLP to triage patients in rural areas, connecting them with the right specialists remotely. We've served 15K patients with 94% satisfaction.",
    industry: 'HealthTech',
    stage: 'Seed',
    askAmount: '3M',
    equity: '9%',
    traction: '15K patients',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 1567,
    comments: 112,
    bookmarks: 289,
    founder: { name: 'Dr. Amara Osei', title: 'CEO & Founder', bio: 'MD from Johns Hopkins, ex-WHO consultant', avatar: null },
    team: [{ name: 'Dr. Amara Osei', role: 'CEO', avatar: null }, { name: 'Tom Nguyen', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)
  },
  {
    id: '5',
    name: 'ClimaTech',
    tagline: 'Real-time climate risk intelligence for infrastructure',
    description: 'ClimaTech provides granular climate risk scores for physical assets using satellite data and ML. Insurance companies and banks use our API to price climate risk accurately.',
    industry: 'CleanTech',
    stage: 'Seed',
    askAmount: '4M',
    equity: '7%',
    traction: '25 enterprise clients',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 934,
    comments: 56,
    bookmarks: 178,
    founder: { name: 'Sophie Laurent', title: 'CEO & Co-founder', bio: 'Ex-NASA climate scientist', avatar: null },
    team: [{ name: 'Sophie Laurent', role: 'CEO', avatar: null }, { name: 'Marcus Webb', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)
  },
  {
    id: '6',
    name: 'FinSight',
    tagline: 'Automated financial reporting for Series A+ startups',
    description: 'FinSight automates investor reporting, board decks, and financial modeling for growth-stage startups. CFOs save 20 hours per month. Used by 300+ startups worldwide.',
    industry: 'FinTech',
    stage: 'Series A',
    askAmount: '8M',
    equity: '11%',
    traction: '300 customers',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 1892,
    comments: 143,
    bookmarks: 367,
    founder: { name: 'Chris Blackwood', title: 'CEO & Founder', bio: 'Ex-Goldman Sachs, YC Alumni', avatar: null },
    team: [{ name: 'Chris Blackwood', role: 'CEO', avatar: null }, { name: 'Ana Ferreira', role: 'CTO', avatar: null }, { name: 'Mike Han', role: 'CFO', avatar: null }],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
  },
  {
    id: '7',
    name: 'DataPulse',
    tagline: 'No-code data pipelines for product teams',
    description: 'DataPulse lets product teams build real-time data pipelines without writing code. Our visual editor connects 200+ data sources. Growing 40% MoM with $150K ARR.',
    industry: 'SaaS',
    stage: 'Seed',
    askAmount: '2.5M',
    equity: '8%',
    traction: '$150K ARR',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 743,
    comments: 38,
    bookmarks: 134,
    founder: { name: 'Nina Kowalski', title: 'CEO & Co-founder', bio: 'Ex-Palantir engineer', avatar: null },
    team: [{ name: 'Nina Kowalski', role: 'CEO', avatar: null }, { name: 'Sam Obi', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000)
  },
  {
    id: '8',
    name: 'HealthAI',
    tagline: 'Predictive diagnostics for chronic disease management',
    description: 'HealthAI uses wearable data and ML to predict chronic disease flare-ups 72 hours in advance. Our FDA-cleared algorithm has 89% accuracy across diabetes and heart disease.',
    industry: 'HealthTech',
    stage: 'Series A',
    askAmount: '15M',
    equity: '10%',
    traction: '100K patients monitored',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 3102,
    comments: 234,
    bookmarks: 567,
    founder: { name: 'Dr. Priya Sharma', title: 'CEO & Co-founder', bio: 'MD-PhD Stanford, ex-Verily', avatar: null },
    team: [{ name: 'Dr. Priya Sharma', role: 'CEO', avatar: null }, { name: 'Carlos Mendez', role: 'CTO', avatar: null }, { name: 'Lisa Chen', role: 'CMO', avatar: null }],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)
  },
  {
    id: '9',
    name: 'CodeMentor',
    tagline: 'AI pair programmer that learns your coding style',
    description: 'CodeMentor is an AI coding assistant that deeply understands your codebase, coding patterns, and team conventions. 3x faster code reviews, 50% fewer bugs in production.',
    industry: 'DeepTech',
    stage: 'Pre-seed',
    askAmount: '1M',
    equity: '12%',
    traction: '5K developers',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 2876,
    comments: 198,
    bookmarks: 489,
    founder: { name: 'Jordan Lee', title: 'CEO & Founder', bio: 'Ex-GitHub engineer, open source contributor', avatar: null },
    team: [{ name: 'Jordan Lee', role: 'CEO', avatar: null }, { name: 'Pat Wilson', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)
  },
  {
    id: '10',
    name: 'AgriSmart',
    tagline: 'Precision agriculture for smallholder farmers in Africa',
    description: 'AgriSmart uses satellite imagery and IoT sensors to give smallholder farmers in Africa real-time crop health insights and weather predictions via SMS. 30% yield improvement.',
    industry: 'CleanTech',
    stage: 'Pre-seed',
    askAmount: '750K',
    equity: '10%',
    traction: '8K farmers',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: null,
    likes: 1456,
    comments: 87,
    bookmarks: 312,
    founder: { name: 'Kwame Asante', title: 'CEO & Founder', bio: 'Agricultural engineer, ex-FAO consultant', avatar: null },
    team: [{ name: 'Kwame Asante', role: 'CEO', avatar: null }, { name: 'Fatima Al-Rashid', role: 'CTO', avatar: null }],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000)
  }
];

export const conversations = [
  {
    id: '1',
    participant: { name: 'Sarah Johnson', role: 'Investor', avatar: null },
    lastMessage: 'Loved your pitch! Can we schedule a call?',
    time: new Date(Date.now() - 5 * 60 * 1000),
    unread: 2,
    messages: [
      { id: '1', text: 'Hi! I just watched your pitch for NeuralPay.', sender: 'them', time: new Date(Date.now() - 30 * 60 * 1000) },
      { id: '2', text: 'The AI fraud detection angle is really compelling.', sender: 'them', time: new Date(Date.now() - 29 * 60 * 1000) },
      { id: '3', text: "Thank you Sarah! We'd love to share more details.", sender: 'me', time: new Date(Date.now() - 20 * 60 * 1000) },
      { id: '4', text: 'Loved your pitch! Can we schedule a call?', sender: 'them', time: new Date(Date.now() - 5 * 60 * 1000) }
    ]
  },
  {
    id: '2',
    participant: { name: 'Michael Chang', role: 'VC Partner', avatar: null },
    lastMessage: "What's your current burn rate?",
    time: new Date(Date.now() - 2 * 60 * 60 * 1000),
    unread: 0,
    messages: [
      { id: '1', text: "Impressive traction numbers. What's your current burn rate?", sender: 'them', time: new Date(Date.now() - 2 * 60 * 60 * 1000) }
    ]
  },
  {
    id: '3',
    participant: { name: 'Andreessen Horowitz', role: 'Investor', avatar: null },
    lastMessage: "We'd like to set up a partner meeting",
    time: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    unread: 1,
    messages: [
      { id: '1', text: "We'd like to set up a partner meeting to discuss Series A", sender: 'them', time: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) }
    ]
  },
  {
    id: '4',
    participant: { name: 'Y Combinator', role: 'Accelerator', avatar: null },
    lastMessage: 'Application deadline is next Friday',
    time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    unread: 0,
    messages: [
      { id: '1', text: 'Application deadline is next Friday. Would love to see you apply!', sender: 'them', time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) }
    ]
  }
];

export const notifications = [
  { id: '1', type: 'view', message: 'Andreessen Horowitz viewed your pitch', time: new Date(Date.now() - 10 * 60 * 1000), read: false },
  { id: '2', type: 'like', message: 'Sarah Johnson liked your pitch video', time: new Date(Date.now() - 30 * 60 * 1000), read: false },
  { id: '3', type: 'match', message: 'New investor match: Sequoia Capital', time: new Date(Date.now() - 2 * 60 * 60 * 1000), read: true },
  { id: '4', type: 'comment', message: 'Michael Chang commented: "Great traction!"', time: new Date(Date.now() - 5 * 60 * 60 * 1000), read: true },
  { id: '5', type: 'view', message: 'Tiger Global viewed your pitch', time: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), read: true },
  { id: '6', type: 'like', message: 'Benchmark Capital bookmarked your pitch', time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), read: true }
];
